# Generated by Django 5.1.1 on 2024-09-10 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='localidadciudad',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='direccion',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='localidadciudad',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='direccion_envio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='medio_pago',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.AddField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='id_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.persona'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='numero',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='medio_pago',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado_factura',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En proceso'), ('C', 'Completado')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='website.persona'),
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
        migrations.DeleteModel(
            name='LocalidadCiudad',
        ),
    ]
