# Generated by Django 5.1.1 on 2024-09-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_pedido_usuario_alter_temausuario_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
    ]
