# Generated by Django 5.1.1 on 2024-09-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_pedido_horario_remove_pedido_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
