# Generated by Django 5.1.1 on 2024-09-11 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_productopedido_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(default=350, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='UsuarioPersona',
        ),
    ]
