# Generated by Django 5.1.1 on 2024-09-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_persona_user_alter_factura_numero_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='horario_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.horario'),
        ),
    ]
