# Generated by Django 5.1.1 on 2024-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_pedido_horario_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopedido',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
